<?php

$config = array(
    'login' => array(
        array(
            'field' => 'user',
            'label' => 'Usuario',
            'rules' => 'required|trim'
        ),
        array(
            'field' => 'pass',
            'label' => 'Contraseña',
            'rules' => 'required|trim'
        )
    ),
    'estudiante/guardar' => array(
        array('field' => 'Enombre', 'label' => 'Nombre Estudiante', 'rules' => 'required|trim'),
        array('field' => 'Eapaterno', 'label' => 'A. Paterno Estudiante', 'rules' => 'required|trim'),
        array('field' => 'Eamaterno', 'label' => 'A. Maaterno Estudiante', 'rules' => 'required|trim'),
        array('field' => 'Efecnac', 'label' => 'Fec. Nac. Estudiante', 'rules' => 'required|trim'),
        array('field' => 'Ecurp', 'label' => 'CURP', 'rules' => 'required|trim'),
        array('field' => 'Edisca', 'label' => 'Discapacidad Estudiante', 'rules' => 'required|trim'),
        array('field' => 'Ecorreo', 'label' => 'Correo Estudiante', 'rules' => 'required|trim'),
        array('field' => 'Esexo', 'label' => 'Sexo Estudiante', 'rules' => 'required|trim'),
        array('field' => 'Eescprod', 'label' => 'Esc. Procedencia', 'rules' => 'required|trim'),
        array('field' => 'Epromedio', 'label' => 'Promedio', 'rules' => 'required|trim'),
        array('field' => 'Ematricula', 'label' => 'Matricula', 'rules' => 'required|trim'),
        array('field' => 'Eturno', 'label' => 'Turno', 'rules' => 'required|callback_Turno'),
        array('field' => 'Egrupo', 'label' => 'Grupo', 'rules' => 'required|callback_Grado_Grupo'),
        array('field' => 'Edescuento', 'label' => 'Descuento Colegiatura', 'rules' => 'required|trim'),
        array('field' => 'Eobserva', 'label' => 'Observaciones', 'rules' => 'required|trim'),
        array('field' => 'Ecalle', 'label' => 'Calle', 'rules' => 'required|trim'),
        array('field' => 'Enumint', 'label' => 'Num. Interior', 'rules' => 'required|trim'),
        array('field' => 'Enumext', 'label' => 'Num. Exterior', 'rules' => 'required|trim'),
        array('field' => 'idPais', 'label' => 'Pais', 'rules' => 'required|trim'),
        array('field' => 'idEdo', 'label' => 'Estado', 'rules' => 'required|trim'),
        array('field' => 'idcodpost', 'label' => 'Cod. Postal', 'rules' => 'required|trim'),
        array('field' => 'iddelmun', 'label' => 'Del. / Mun.', 'rules' => 'required|trim'),
        array('field' => 'idcol', 'label' => 'Colonia', 'rules' => 'required|trim'),
        array('field' => 'Pnombre', 'label' => 'Nombre Padre', 'rules' => 'required|trim'),
        array('field' => 'Papaterno', 'label' => 'A. Paterno Padre', 'rules' => 'required|trim'),
        array('field' => 'Pamaterno', 'label' => 'A. Materno Padre', 'rules' => 'required|trim'),
        array('field' => 'Pfecnac', 'label' => 'Fec. Nac. Padre', 'rules' => 'required|trim'),
        array('field' => 'Pdisca', 'label' => 'Discapacidad Padre', 'rules' => 'required|trim'),
        array('field' => 'Pcorreo', 'label' => 'Correo Padre', 'rules' => 'required|trim'),
        array('field' => 'Psexo', 'label' => 'Sexo Padre', 'rules' => 'required|trim'),
        array('field' => 'Pprofesion', 'label' => 'Profesion Padre', 'rules' => 'required|trim'),
        array('field' => 'Pingreso', 'label' => 'Ingreso Padre', 'rules' => 'required|trim'),
        array('field' => 'Poficina', 'label' => 'Num. Oficina Padre', 'rules' => 'required|trim'),
        array('field' => 'Pcel', 'label' => 'Num. Cel. Padre', 'rules' => 'required|trim'),
        array('field' => 'Pobserva', 'label' => 'Observacacion Padre', 'rules' => 'required|trim'),
        array('field' => 'Mnombre', 'label' => 'Nombre Madre', 'rules' => 'required|trim'),
        array('field' => 'Mapaterno', 'label' => 'A. Paterno Madre', 'rules' => 'required|trim'),
        array('field' => 'Mamaterno', 'label' => 'A. Materno Madre', 'rules' => 'required|trim'),
        array('field' => 'Mfecnac', 'label' => 'FEc. Nac. Madre', 'rules' => 'required|trim'),
        array('field' => 'Mdisca', 'label' => 'Discapacidad Madre', 'rules' => 'required|trim'),
        array('field' => 'Mcorreo', 'label' => 'Correo Madre', 'rules' => 'required|trim'),
        array('field' => 'Msexo', 'label' => 'Sexo Madre', 'rules' => 'required|trim'),
        array('field' => 'Mprofesion', 'label' => 'Profesion Madre', 'rules' => 'required|trim'),
        array('field' => 'Mingreso', 'label' => 'Ingreso Madre', 'rules' => 'required|trim'),
        array('field' => 'Moficina', 'label' => 'Num. Oficna Madre', 'rules' => 'required|trim'),
        array('field' => 'Mcel', 'label' => 'Num. Cel. Madre', 'rules' => 'required|trim'),
        array('field' => 'Mobserva', 'label' => 'Observaciones Madre', 'rules' => 'required|trim'),
    ),
    'docente' => array(
        array('field' => 'Enombre', 'label' => 'Nombre Estudiante', 'rules' => 'required|trim'),
        array('field' => 'Eapaterno', 'label' => 'A. Paterno Estudiante', 'rules' => 'required|trim'),
        array('field' => 'Eamaterno', 'label' => 'A. Maaterno Estudiante', 'rules' => 'required|trim'),
        array('field' => 'Efecnac', 'label' => 'Fec. Nac. Estudiante', 'rules' => 'required|trim'),
        array('field' => 'Ecurp', 'label' => 'CURP', 'rules' => 'required|trim'),
        array('field' => 'Edisca', 'label' => 'Discapacidad Estudiante', 'rules' => 'required|trim'),
        array('field' => 'Ecorreo', 'label' => 'Correo Estudiante', 'rules' => 'required|trim'),
        array('field' => 'Esexo', 'label' => 'Sexo Estudiante', 'rules' => 'required|trim'),
        array('field' => 'Doficina', 'label' => 'Num. Oficna', 'rules' => 'required|trim'),
        array('field' => 'Dcel', 'label' => 'Num. Celular', 'rules' => 'required|trim'),
        array('field' => 'Eescprod', 'label' => 'Esc. Procedencia', 'rules' => 'required|trim'),
        array('field' => 'Eturno', 'label' => 'Turno', 'rules' => 'required|callback_Turno'),
        array('field' => 'Emateria[]', 'label' => 'Materia', 'rules' => 'required|callback_Materia'),
        array('field' => 'Eobserva', 'label' => 'Observaciones', 'rules' => 'required|trim'),
        array('field' => 'Ecalle', 'label' => 'Calle', 'rules' => 'required|trim'),
        array('field' => 'Enumint', 'label' => 'Num. Interior', 'rules' => 'required|trim'),
        array('field' => 'Enumext', 'label' => 'Num. Exterior', 'rules' => 'required|trim'),
        array('field' => 'idPais', 'label' => 'Pais', 'rules' => 'required|trim'),
        array('field' => 'idEdo', 'label' => 'Estado', 'rules' => 'required|trim'),
        array('field' => 'idcodpost', 'label' => 'Cod. Postal', 'rules' => 'required|trim'),
        array('field' => 'iddelmun', 'label' => 'Del. / Mun.', 'rules' => 'required|trim'),
        array('field' => 'idcol', 'label' => 'Colonia', 'rules' => 'required|trim'),
    ),
    'empleado' => array(
        array('field' => 'Enombre', 'label' => 'Nombre Estudiante', 'rules' => 'required|trim'),
        array('field' => 'Eapaterno', 'label' => 'A. Paterno Estudiante', 'rules' => 'required|trim'),
        array('field' => 'Eamaterno', 'label' => 'A. Maaterno Estudiante', 'rules' => 'required|trim'),
        array('field' => 'Efecnac', 'label' => 'Fec. Nac. Estudiante', 'rules' => 'required|trim'),
        array('field' => 'Ecurp', 'label' => 'CURP', 'rules' => 'required|trim'),
        array('field' => 'Ecorreo', 'label' => 'Correo Estudiante', 'rules' => 'required|trim'),
        array('field' => 'Esexo', 'label' => 'Sexo Estudiante', 'rules' => 'required|trim'),
        array('field' => 'Doficina', 'label' => 'Num. Oficna', 'rules' => 'required|trim'),
        array('field' => 'Dcel', 'label' => 'Num. Celular', 'rules' => 'required|trim'),
        array('field' => 'Epuesto', 'label' => 'Puesto', 'rules' => 'required|trim'),
        array('field' => 'Eturno', 'label' => 'Turno', 'rules' => 'required|callback_Turno'),
        array('field' => 'Eobserva', 'label' => 'Observaciones', 'rules' => 'required|trim'),
        array('field' => 'Ecalle', 'label' => 'Calle', 'rules' => 'required|trim'),
        array('field' => 'Enumint', 'label' => 'Num. Interior', 'rules' => 'required|trim'),
        array('field' => 'Enumext', 'label' => 'Num. Exterior', 'rules' => 'required|trim'),
        array('field' => 'idPais', 'label' => 'Pais', 'rules' => 'required|trim'),
        array('field' => 'idEdo', 'label' => 'Estado', 'rules' => 'required|trim'),
        array('field' => 'idcodpost', 'label' => 'Cod. Postal', 'rules' => 'required|trim'),
        array('field' => 'iddelmun', 'label' => 'Del. / Mun.', 'rules' => 'required|trim'),
        array('field' => 'idcol', 'label' => 'Colonia', 'rules' => 'required|trim'),
    ),
    'reinscripcion' => array(
        array('field' => 'Egrupo', 'label' => 'Grupo', 'rules' => 'required|callback_Grado_Grupo'),
        array('field' => 'DescBaja', 'label' => 'Observaciones', 'rules' => 'required|trim'),
    ),
    'pago_servicios' => array(
        array('field' => 'DescBaja', 'label' => 'Observaciones', 'rules' => 'required|trim'),
    ),
);
